<?php

namespace OptionBundle\Repository;

/**
 * OptionPriceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OptionPriceRepository extends \Doctrine\ORM\EntityRepository
{
}
