<?php

namespace OptionBundle\Repository;

use OptionBundle\Repository\Infrastructure\AbstractRepository;

/**
 * OptionPriceRepository
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OptionPriceRepository extends AbstractRepository
{

}
