<?php

namespace OptionBundle\Repository;

use OptionBundle\Repository\Infrastructure\AbstractRepository;

/**
 * OptionContractRepository
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OptionContractRepository extends AbstractRepository
{

}
