<?php

namespace OptionBundle\Repository;

/**
 * OptionContractRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OptionContractRepository extends \Doctrine\ORM\EntityRepository
{
}
