<?php

namespace OptionBundle\Repository;

use OptionBundle\Repository\Infrastructure\AbstractRepository;

/**
 * SymbolRepository
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SymbolRepository extends AbstractRepository
{

}
