<?php

namespace OptionBundle\Repository;

use OptionBundle\Entity\Symbol;
use OptionBundle\Repository\Infrastructure\AbstractRepository;

/**
 * SymbolRepository
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SymbolRepository extends AbstractRepository
{

    /**
     * @param string $symbolName
     * @return Symbol|null
     */
    public function findOneBySymbol(string $symbolName): Symbol
    {
        return $this->findOneBy([
            'symbol' => $symbolName,
        ]);
    }
}
