services:
    optionboard.price_collector:
        class: OptionBundle\Service\PriceCollector
        arguments: ["@optionboard.futures_repository"]

    optionboard.futures_repository:
        class: OptionBundle\Repository\FuturesRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments: [OptionBundle\Entity\Futures]
