services:
    optionboard.futures_repository:
        class: OptionBundle\Repository\FuturesRepository
        factory_method: getRepository
        factory_service: doctrine.orm.entity_manager
        arguments:
            - OptionBundle\Entity\Futures
